version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: db

volumes:
  postgres:
