version: "3.9"

services:
  rag-bot:
    build: .
    container_name: rag-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://root:1234@db:5432/db
      - MSG_EXPIRY_SEC=604800
      - MAX_EMBED_DIST=1
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_CLIENT_ID=${BOT_CLIENT_ID}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
